import D20.Money
alias D20.Item

defmodule D20 do
  @alignments [
    "Chaotic Evil",
    "Neutral Evil",
    "Lawful Evil",
    "Chaotic Neutral",
    "Neutral",
    "Lawful Neutral",
    "Chaotic Good",
    "Neutral Good",
    "Lawful Good"
  ]
  def alignments, do: @alignments

  @items [
    %Item{cost: gp_to_cp(2), weight: 2, name: "Abacus"},
    %Item{cost: gp_to_cp(25), weight: 1, description: "As an action, you can splash the contents of this vial onto a creature within 5 feet of you or throw the vial up to 20 feet, shattering it on impact. In either case, make a ranged attack against a creature or object, treating the acid as an improvised weapon. On a hit, the target takes 2d6 acid damage.", name: "Acid (vial)"},
    %Item{cost: gp_to_cp(50), weight: 1, description: "This sticky, adhesive fluid ignites when exposed to air. As an action, you can throw this flask up to 20 feet, shattering it on impact. Make a ranged attack against a creature or object, treating the  alchemist's fire as an improvised weapon. On a hit, the target takes 1d4 fire damage at the start of each of its turns. A creature can end this damage by using its action to make a DC 10 Dexterity check to extinguish the flames.", name: "Alchemist's fire (flask)"},
    %Item{cost: gp_to_cp(2), weight: 5, name: "Backpack"},
    %Item{cost: gp_to_cp(1), weight: 2, description: "As an action, you can spill these tiny metal balls from their pouch to cover a level area 10 feet square. A creature moving across the covered area must succeed on a DC 10 Dexterity saving throw or fall prone. A creature moving through the area at half speed doesn't need to make the saving throw.", name: "Ball bearings (bag of 1,000)"},
    %Item{cost: gp_to_cp(2), weight: 70, name: "Barrel"},
    %Item{cost: sp_to_cp(4), weight: 2, name: "Basket"},
    %Item{cost: gp_to_cp(1), weight: 7, name: "Bedroll"},
    %Item{cost: gp_to_cp(1), weight: 0, name: "Bell"},
    %Item{cost: sp_to_cp(5), weight: 3, name: "Blanket"},
    %Item{cost: gp_to_cp(1), weight: 5, description: "A set of pulleys with a cable threaded through them and a hook to attach to objects, a block and tackle allows you to hoist up to four times the weight you can normally lift.", name: "Block and tackle"},
    %Item{cost: gp_to_cp(25), weight: 5, description: "A book might contain poetry, historical accounts, information pertaining to a particular field of lore, diagrams and notes on gnomish contraptions, or just about anything else that can be represented using text or pictures. A book of spells is a spellbook (described later in this section).", name: "Book"},
    %Item{cost: gp_to_cp(2), weight: 2, name: "Bottle, glass"},
    %Item{cost: 5, weight: 2, name: "Bucket"},
    %Item{cost: gp_to_cp(1), weight: 2, description: "As an action, you can spread a single bag of caltrops to cover a 5-foot-square area. Any creature that enters the area must succeed on a DC 15 Dexterity saving throw or stop moving and take 1 piercing damage. Until the creature regains at least 1 hit point, its walking speed is reduced by 10 feet. A creature moving through the area at half speed doesn't need to make the saving throw.", name: "Caltrops (bag of 20)"},
    %Item{cost: 1, weight: 0, description: "For 1 hour, a candle sheds bright light in a 5-foot radius and dim light for an additional 5 feet.", name: "Candle"},
    %Item{cost: gp_to_cp(1), weight: 1, description: "This wooden case can hold up to twenty crossbow bolts. Case, Map or Scroll. This cylindrical leather case can hold up to ten rolled-up sheets of paper or five rolled-up sheets of parchment.", name: "Case, crossbow bolt"},
    %Item{cost: gp_to_cp(1), weight: 1, name: "Case, map or scroll"},
    %Item{cost: gp_to_cp(5), weight: 10, description: "A chain has 10 hit points. It can be burst with a successful DC 20 Strength check.", name: "Chain (10 feet)"},
    %Item{cost: 1, weight: 0, name: "Chalk (1 piece)"},
    %Item{cost: gp_to_cp(5), weight: 25, name: "Chest"},
    %Item{cost: gp_to_cp(25), weight: 12, description: "A climber's kit includes special pitons, boot tips, gloves, and a harness. You can use the climber's kit as an action to anchor yourself; when you do, you can't fall more than 25 feet from the point where you anchored yourself, and you can't climb more than 25 feet away from that point without undoing the anchor.", name: "Climber's kit"},
    %Item{cost: sp_to_cp(5), weight: 3, name: "Clothes, common"},
    %Item{cost: gp_to_cp(5), weight: 4, name: "Clothes, costume"},
    %Item{cost: gp_to_cp(15), weight: 6, name: "Clothes, fine"},
    %Item{cost: gp_to_cp(2), weight: 4, name: "Clothes, traveler's"},
    %Item{cost: gp_to_cp(25), weight: 2, description: "A component pouch is a small, watertight leather belt pouch that has compartments to hold all the material components and other special items you need to cast your spells, except for those components that have a specific cost (as indicated in a spell's description).", name: "Component pouch"},
    %Item{cost: gp_to_cp(2), weight: 5, description: "Using a crowbar grants advantage to Strength checks where the crowbar's leverage can be applied.", name: "Crowbar"},
    %Item{cost: gp_to_cp(1), weight: 4, description: "This kit includes a wooden rod, silken line, corkwood bobbers, steel hooks, lead sinkers, velvet lures, and narrow netting. Healer's Kit. This kit is a leather pouch containing bandages, salves, and splints. The kit has ten uses. As an action, you can expend one use of the kit to stabilize a creature that has 0 hit points, without needing to make a Wisdom (Medicine) check.", name: "Fishing tackle"},
    %Item{cost: 2, weight: 1, name: "Flask or tankard"},
    %Item{cost: gp_to_cp(2), weight: 4, name: "Grappling hook"},
    %Item{cost: gp_to_cp(1), weight: 3, name: "Hammer"},
    %Item{cost: gp_to_cp(2), weight: 10, name: "Hammer, sledge"},
    %Item{cost: gp_to_cp(5), weight: 3, name: "Healer's kit"},
    %Item{cost: gp_to_cp(25), weight: 1, name: "Hourglass"},
    %Item{cost: gp_to_cp(5), weight: 25, description: "When you use your action to set it, this trap forms a saw-toothed steel ring that snaps shut when a creature steps on a pressure plate in the center. The trap is affixed by a heavy chain to an immobile object, such as a tree or a spike driven into the ground. A creature that steps on the plate must succeed on a DC 13 Dexterity saving throw or take 1d4 piercing damage and stop moving. Thereafter, until the creature breaks free of the trap, its movement is limited by the length of the chain (typically 3 feet long). A creature can use its action to make a DC 13 Strength check, freeing itself or another creature within its reach on a success. Each failed check deals 1 piercing damage to the trapped creature.", name: "Hunting trap"},
    %Item{cost: gp_to_cp(10), weight: 0, name: "Ink (1 ounce bottle)"},
    %Item{cost: 2, weight: 0, name: "Ink pen"},
    %Item{cost: 2, weight: 4, name: "Jug or pitcher"},
    %Item{cost: sp_to_cp(1), weight: 25, name: "Ladder (10-foot)"},
    %Item{cost: sp_to_cp(5), weight: 1, description: "A lamp casts bright light in a 15-foot radius and dim light for an additional 30 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil.", name: "Lamp"},
    %Item{cost: gp_to_cp(10), weight: 2, description: "A bullseye lantern casts bright light in a 60-foot cone and dim light for an additional 60 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil.", name: "Lantern, bullseye"},
    %Item{cost: gp_to_cp(5), weight: 2, description: "A hooded lantern casts bright light in a 30-foot radius and dim light for an additional 30 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil. As an action, you can lower the hood, reducing the light to dim light in a 5-foot radius.", name: "Lantern, hooded"},
    %Item{cost: gp_to_cp(10), weight: 1, description: "A key is provided with the lock. Without the key, a creature proficient with thieves' tools can pick this lock with a successful DC 15 Dexterity check. Your DM may decide that better locks are available for higher prices.", name: "Lock"},
    %Item{cost: sp_to_cp(2), weight: 1, description: "This tin box contains a cup and simple cutlery. The box clamps together, and one side can be used as a cooking pan and the other as a plate or shallow bowl.", name: "Mess kit"},
    %Item{cost: gp_to_cp(100), weight: 0, description: "This lens allows a closer look at small objects. It is also useful as a substitute for flint and steel when starting fires. Lighting a fire with a magnifying glass requires light as bright as sunlight to focus, tinder to ignite, and about 5 minutes for the fire to ignite. A magnifying glass grants advantage on any ability check made to appraise or inspect an item that is small or highly detailed.", name: "Magnifying glass"},
    %Item{cost: gp_to_cp(2), weight: 6, description: "These metal restraints can bind a Small or Medium creature. Escaping the manacles requires a successful DC 20 Dexterity check. Breaking them requires a successful DC 20 Strength check. Each set of manacles comes with one key. Without the key, a creature proficient with thieves' tools can pick the manacles' lock with a successful DC 15 Dexterity check. Manacles have 15 hit points.", name: "Manacles"},
    %Item{cost: gp_to_cp(5), weight: 1, name: "Mirror, steel"},
    %Item{cost: sp_to_cp(1), weight: 1, description: "Oil usually comes in a clay flask that holds 1 pint. As an action, you can splash the oil in this flask onto a creature within 5 feet of you or throw it up to 20 feet, shattering it on impact. Make a ranged attack against a target creature or object, treating the oil as an improvised weapon. On a hit, the target is covered in oil. If the target takes any fire damage before the oil dries (after 1 minute), the target takes an additional 5 fire damage from the burning oil. You can also pour a flask of oil on the ground to cover a 5-foot-square area, provided that the surface is level. If lit, the oil burns for 2 rounds and deals 5 fire damage to any creature that enters the area or ends its turn in the area. A creature can take this damage only once per turn.", name: "Oil (flask)"},
    %Item{cost: sp_to_cp(2), weight: 0, name: "Paper (one sheet)"},
    %Item{cost: sp_to_cp(1), weight: 0, name: "Parchment (one sheet)"},
    %Item{cost: gp_to_cp(5), weight: 0, name: "Perfume (vial)"},
    %Item{cost: gp_to_cp(2), weight: 10, name: "Pick, miner's"},
    %Item{cost: 5, weight: 0.25, name: "Piton"},
    %Item{cost: gp_to_cp(100), weight: 0, description: "You can use the poison in this vial to coat one slashing or piercing weapon or up to three pieces of ammunition. Applying the poison takes an action. A creature hit by the poisoned weapon or ammunition must make a DC 10 Constitution saving throw or take 1d4 poison damage. Once applied, the poison retains potency for 1 minute before drying.", name: "Poison, basic (vial)"},
    %Item{cost: 5, weight: 7, name: "Pole (10-foot)"},
    %Item{cost: gp_to_cp(2), weight: 10, name: "Pot, iron"},
    %Item{cost: gp_to_cp(50), weight: 0.5, description: "A character who drinks the magical red fluid in this vial regains 2d4 + 2 hit points. Drinking or administering a potion takes an action.", name: "Potion of healing"},
    %Item{cost: sp_to_cp(5), weight: 1, description: "A cloth or leather pouch can hold up to 20 sling bullets or 50 blowgun needles, among other things. A compartmentalized pouch for holding spell components is called a component pouch (described earlier in this section).", name: "Pouch"},
    %Item{cost: gp_to_cp(1), weight: 1, description: "A quiver can hold up to 20 arrows.", name: "Quiver"},
    %Item{cost: gp_to_cp(4), weight: 35, description: "You can use a portable ram to break down doors. When doing so, you gain a +4 bonus on the Strength check. One other character can help you use the ram, giving you advantage on this check.", name: "Ram, portable"},
    %Item{cost: sp_to_cp(5), weight: 2, description: "Rations consist of dry foods suitable for extended travel, including jerky, dried fruit, hardtack, and nuts.", name: "Rations (1 day)"},
    %Item{cost: gp_to_cp(1), weight: 4, name: "Robes"},
    %Item{cost: gp_to_cp(1), weight: 10, description: "Rope, whether made of hemp or silk, has 2 hit points and can be burst with a DC 17 Strength check.", name: "Rope, hempen (50 feet)"},
    %Item{cost: gp_to_cp(10), weight: 5, description: "Rope, whether made of hemp or silk, has 2 hit points and can be burst with a DC 17 Strength check.", name: "Rope, silk (50 feet)"},
    %Item{cost: 1, weight: 0.5, name: "Sack"},
    %Item{cost: gp_to_cp(5), weight: 3, description: "A scale includes a small balance, pans, and a suitable assortment of weights up to 2 pounds. With it, you can measure the exact weight of small objects, such as raw precious metals or trade goods, to help determine their worth.", name: "Scale, merchant's"},
    %Item{cost: sp_to_cp(5), weight: 0, name: "Sealing wax"},
    %Item{cost: gp_to_cp(2), weight: 5, name: "Shovel"},
    %Item{cost: 5, weight: 0, name: "Signal whistle"},
    %Item{cost: gp_to_cp(5), weight: 0, name: "Signet ring"},
    %Item{cost: 0, weight: 0, name: "String (10 feet)"},
    %Item{cost: 2, weight: 0, name: "Soap"},
    %Item{cost: gp_to_cp(50), weight: 3, description: "Essential for wizards, a spellbook is a leather-bound tome with 100 blank vellum pages suitable for recording spells.", name: "Spellbook"},
    %Item{cost: gp_to_cp(1), weight: 5, name: "Spikes, iron (10)"},
    %Item{cost: gp_to_cp(100), weight: 1, description: "Objects viewed through a spyglass are magnified to twice their size.", name: "Spyglass"},
    %Item{cost: gp_to_cp(2), weight: 20, description: "A simple and portable canvas shelter, a tent sleeps two.", name: "Tent, two-person"},
    %Item{cost: sp_to_cp(5), weight: 1, description: "This small container holds flint, fire steel, and tinder (usually dry cloth soaked in light oil) used to kindle a fire. Using it to light a torch—or anything else with abundant, exposed fuel—takes an action. Lighting any other fire takes 1 minute.", name: "Tinderbox"},
    %Item{cost: 1, weight: 1, description: "A torch burns for 1 hour, providing bright light in a 20-foot radius and dim light for an additional 20 feet. If you make a melee attack with a burning torch and hit, it deals 1 fire damage.", name: "Torch"},
    %Item{cost: gp_to_cp(1), weight: 0, name: "Vial"},
    %Item{cost: sp_to_cp(2), weight: 5 , name: "Waterskin"},
    %Item{cost: 1, weight: 1, name: "Whetstone"},
    %Item{cost: 0, weight: 0, name: "Block of incense"},
    %Item{cost: 0, weight: 0, name: "Alms box"},
    %Item{cost: 0, weight: 0, name: "Censer"},
    %Item{cost: 0, weight: 0, name: "Vestments"},
    %Item{cost: 0, weight: 0, name: "Bag of sand"},
    %Item{cost: 0, weight: 0, name: "Knife (small)"},
    %Item{cost: 2500, weight: 5, name: "Book of lore"}
  ]
  def items, do: @items
end
